changelog:
  exclude:
    labels:
      - ignore-for-release
      - release minor
      - release patch
    authors:
      - github-actions[bot]
  categories:
    - title: Production code updates
      labels:
        - dependencies
        - enhancement
    - title: Other Changes
      labels:
        - '*'
