name: 'npm audit action'
description: 'run npm audit'
author: 'Naoki Oketani <okepy.naoki@gmail.com>'
inputs:
  github_context:
    description: 'The `github` context'
    required: false
  token:
    description: 'GitHub access token used to create an issue'
    required: true
  issue_assignees:
    description: 'Issue assignees (separated by commma)'
    required: false
  issue_labels:
    description: 'Issue assignees (separated by commma)'
    required: false
  issue_title:
    description: 'Issue title'
    default: 'npm audit found vulnerabilities'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'orange'
