name: "update dist/index.js"
on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository code
      uses: actions/checkout@v4
    - name: install dependencies
      run: |
        npm ci
    - name: format TypeScript code
      run: |
        npm run format
    - name: compile TypeScript code into dist/index.js
      run: |
        npm run package
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore(build): automated change"
